name: Deploy HustleMode.ai to Azure Functions

on:
  push:
    branches:
      - main
    paths:
      - 'azure-functions-deploy/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './azure-functions-deploy'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'hustlemode-premium-bot'
        package: './azure-functions-deploy'
        publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}

    - name: 'Deployment Success'
      run: echo "🔥 HustleMode.ai Azure Functions deployed successfully! STAY HARD! 💪" 