name: Deploy HustleMode.ai to Azure Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure-functions-deploy'
  PYTHON_VERSION: '3.11'

jobs:
  anti-bloat-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Run Anti-Bloat Check'
      run: |
        chmod +x scripts/check-bloat.sh
        ./scripts/check-bloat.sh

    - name: 'Report Results'
      if: success()
      run: echo "🎯 Repository is clean and bloat-free! 🔥"
      
    - name: 'Report Violations'
      if: failure()
      run: |
        echo "❌ Repository bloat detected!"
        echo "Review the violations above and fix them before merging."
        exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: anti-bloat-check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Setup Python version'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install dependencies'
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        echo "📦 Installing Python dependencies..."
        mkdir -p .python_packages/lib/site-packages
        pip install -r requirements.txt --target .python_packages/lib/site-packages
        echo "✅ Dependencies installed. Checking structure:"
        ls -la
        echo "📁 Contents of .python_packages/lib/site-packages/:"
        ls -la .python_packages/lib/site-packages/

    - name: 'Deploy via ZIP Deploy to Azure Functions'
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        echo "🚀 Starting ZIP Deploy to Azure Functions..."
        
        # Create deployment zip
        echo "📦 Creating deployment package..."
        echo "📁 Files to be zipped:"
        find . -type f | head -20
        zip -r deploy.zip .
        echo "✅ Zip created. Size:"
        ls -lh deploy.zip
        echo "📁 Contents of zip:"
        unzip -l deploy.zip | head -20
        
        # Extract publish profile details
        PUBLISH_PROFILE='${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FFEB2282094642A1A8B5E3AFAE67C0DC }}'
        
        # Extract username and password from publish profile
        USERNAME=$(echo "$PUBLISH_PROFILE" | grep -o 'userName="[^"]*"' | cut -d'"' -f2)
        PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -o 'userPWD="[^"]*"' | cut -d'"' -f2)
        
        # Deploy via ZIP Deploy API
        curl -X POST \
          -u "$USERNAME:$PASSWORD" \
          -H "Content-Type: application/zip" \
          --data-binary @deploy.zip \
          "https://hustlemode-api.scm.azurewebsites.net/api/zipdeploy?isAsync=false"
        
        echo "📦 ZIP Deploy completed!"

    - name: 'Verify Deployment'
      run: |
        echo "🔍 Verifying deployment..."
        sleep 30  # Wait for deployment to settle
        
        # Check if the function app is responding (basic connectivity)
        echo "🏥 Testing function app connectivity..."
        HEALTH_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://hustlemode-api.azurewebsites.net/")
        
        if [ "$HEALTH_RESPONSE" -eq 200 ] || [ "$HEALTH_RESPONSE" -eq 404 ]; then
          echo "✅ Function app is responding (HTTP $HEALTH_RESPONSE)"
        else
          echo "❌ Function app connectivity failed (HTTP $HEALTH_RESPONSE)"
          echo "🔍 Checking function app status..."
          curl -v "https://hustlemode-api.azurewebsites.net/"
          exit 1
        fi
        
        # Note: Function endpoints require authentication keys
        echo "ℹ️  Function endpoints require authentication keys for testing"
        echo "🔑 Health endpoint: https://hustlemode-api.azurewebsites.net/api/health?code={function_key}"
        echo "📱 WhatsApp webhook: https://hustlemode-api.azurewebsites.net/api/messaging/whatsapp?code={function_key}"
        echo "🤖 Assistant API: https://hustlemode-api.azurewebsites.net/api/assistants?code={function_key}"
        
        # Test if function app deployment was successful by checking scm endpoint
        echo "🔍 Checking deployment status..."
        SCM_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://hustlemode-api.scm.azurewebsites.net/")
        
        if [ "$SCM_RESPONSE" -eq 200 ] || [ "$SCM_RESPONSE" -eq 401 ]; then
          echo "✅ SCM endpoint accessible - deployment likely successful (HTTP $SCM_RESPONSE)"
        else
          echo "⚠️  SCM endpoint returned HTTP $SCM_RESPONSE"
        fi

    - name: 'Deployment Success'
      run: echo "🔥 HustleMode.ai Azure Functions deployed successfully! 💪" 