name: Deploy HustleMode.ai to Azure Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  anti-bloat-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Run Anti-Bloat Check'
      run: |
        chmod +x scripts/check-bloat.sh
        ./scripts/check-bloat.sh

    - name: 'Report Results'
      if: success()
      run: echo "🎯 Repository is clean and bloat-free! 🔥"
      
    - name: 'Report Violations'
      if: failure()
      run: |
        echo "❌ Repository bloat detected!"
        echo "Review the violations above and fix them before merging."
        exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: anti-bloat-check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './azure-functions-deploy'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    # Uncomment the following step if you create AZURE_CREDENTIALS secret
    # - name: 'Azure Login'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'hustlemode-premium-bot'
        package: './azure-functions-deploy'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: 'Deployment Success'
      run: echo "🔥 HustleMode.ai Azure Functions deployed successfully! STAY HARD! 💪" 