name: Deploy HustleMode.ai to Azure Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure-functions-deploy'
  PYTHON_VERSION: '3.11'

jobs:
  anti-bloat-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Run Anti-Bloat Check'
      run: |
        chmod +x scripts/check-bloat.sh
        ./scripts/check-bloat.sh

    - name: 'Report Results'
      if: success()
      run: echo "🎯 Repository is clean and bloat-free! 🔥"
      
    - name: 'Report Violations'
      if: failure()
      run: |
        echo "❌ Repository bloat detected!"
        echo "Review the violations above and fix them before merging."
        exit 1

  build:
    runs-on: ubuntu-latest
    needs: anti-bloat-check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Setup Python version'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Create and start virtual environment'
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: 'Install dependencies'
      run: |
        source venv/bin/activate
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        pip install -r requirements.txt

    - name: 'Zip artifact for deployment'
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        zip -r release.zip ./*

    - name: 'Upload artifact for deployment job'
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: 'Download artifact from build job'
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: 'Unzip artifact for deployment'
      run: unzip release.zip     

    - name: 'Deploy via ZIP Deploy to Azure Functions'
      run: |
        echo "🚀 Starting ZIP Deploy to Azure Functions..."
        
        # Create zip for deployment
        zip -r deploy.zip . -x "*.zip"
        
        # Extract publish profile details
        PUBLISH_PROFILE='${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FFEB2282094642A1A8B5E3AFAE67C0DC }}'
        
        # Extract username and password from publish profile
        USERNAME=$(echo "$PUBLISH_PROFILE" | grep -o 'userName="[^"]*"' | cut -d'"' -f2)
        PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -o 'userPWD="[^"]*"' | cut -d'"' -f2)
        
        # Deploy via ZIP Deploy API
        curl -X POST \
          -u "$USERNAME:$PASSWORD" \
          -H "Content-Type: application/zip" \
          --data-binary @deploy.zip \
          "https://hustlemode-premium-bot.scm.azurewebsites.net/api/zipdeploy?isAsync=false"
        
        echo "📦 ZIP Deploy completed!"

    - name: 'Deployment Success'
      run: echo "🔥 HustleMode.ai Azure Functions deployed successfully! STAY HARD! 💪" 